Push 25.1.0

diff --git a/installer/resources/user_data/login_node/01_user_data.sh.j2 b/installer/resources/user_data/login_node/01_user_data.sh.j2
--- a/installer/resources/user_data/login_node/01_user_data.sh.j2
+++ b/installer/resources/user_data/login_node/01_user_data.sh.j2
@@ -5,32 +5,63 @@
 
 # Important: Keep this file < 16 KBs (AWS EC2 UserData requirement)
 
+# Load common logging feature
 {% include "templates/linux/common/log.sh.j2" %}
 
+log_info "User Data Start Date: $(date)"
+
+# Load packages management functions
+{% include "templates/linux/system_packages/packages_management.sh.j2" %}
+
+# Load common File Download wrapper
+{% include "templates/linux/common/file_download.sh.j2" %}
+
+# Configure HTTP proxy if any
 {% include "templates/linux/http_proxy.sh.j2" %}
 
 source /etc/environment
 
 {% if context.get("/configuration/BaseOS") == "centos7" %}
+  # CentOS7 is EOL, manual patch to support Yum repo
   {% include "templates/linux/patch_centos7_repos.sh.j2" %}
 {% endif %}
 
-{% include "templates/linux/packages_management.sh.j2" %}
-
+# Install awscli
 {% include "templates/linux/awscli.sh.j2" %}
 
+# Load custom wrappers
 {% include "templates/linux/common/wrapper_awscli.sh.j2" %}
+{% include "templates/linux/common/wrapper_imds.sh.j2" %}
+{% include "templates/linux/common/setup_environment_file.sh.j2" %}
 
+# Install AWS Systems Manager agent
 {% include "templates/linux/aws_ssm_agent.sh.j2" %}
 
-{% include "templates/linux/mount_apps_data.sh.j2" %}
+# Note: Log generated prior to filesystems mount will be automatically copied over the POST_FILESYSTEM_MOUNT_LOGS_FOLDER post filesystems mount
+PRE_FILESYSTEM_MOUNT_LOGS_FOLDER="/root/soca_boostrap_$(instance_id)/logs"
+POST_FILESYSTEM_MOUNT_LOGS_FOLDER="{{ context.get("/job/BootstrapPath") }}/$(hostname -s)/$(date +%s)"
 
-# Wait until initial Controller script has completed as this is the one setting up the filesystem structure
-NODE_BOOTSTRAP_FOLDER="{{ context.get("/job/BootstrapPath") }}/$(hostname -s)/$(date +%s)"
+# Remove any previous references of SOCA to the environment file (if any)
+cp /etc/environment /etc/environment.original.$(date +%s)
+sed -i '/[SOCA_DO_NOT_DELETE]/d' /etc/environment
 
+# Set Environment Variables
+set_environment_variable "AWS_DEFAULT_REGION" "{{ context.get("/configuration/Region") }}"
+set_environment_variable "SOCA_BOOTSTRAP_ASSETS_FOLDER" "/root/soca_boostrap_$(instance_id)"
+set_environment_variable "SOCA_BOOTSTRAP_LOGS_FOLDER" ${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}
+set_environment_variable "SOCA_CLUSTER_ID" "{{ context.get("/configuration/ClusterId") }}"
+
+# Create SOCA Bootstrap structure
+mkdir -p ${SOCA_BOOTSTRAP_ASSETS_FOLDER}
+mkdir -p ${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}
+
+# Mount Filesystems
+{% include "templates/linux/filesystems_automount.sh.j2" %}
+
+# Wait until SOCA is ready
 VERIFY_FILE_COUNT=0
 while [[ ! -d "/apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_node_bootstrap/" ]]; do
-     echo "Waiting for the initial Controller setup sequence, checking if /apps/soca/{{ context.get("/configuration/ClusterId") }} exist,  ... trying again in 60 seconds"
+     log_info "/apps/soca/{{ context.get("/configuration/ClusterId") }} not ready yet"
      if [[ ${VERIFY_FILE_COUNT} -gt 30 ]]; then
       exit_fail "Unable to verify filesystem"
      fi
@@ -38,22 +69,25 @@ while [[ ! -d "/apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_
     sleep 60
 done
 
-mkdir -p "${NODE_BOOTSTRAP_FOLDER}"
+# Post Filesystems Mount, override SOCA_BOOTSTRAP_LOGS_FOLDER to point to the shared filesystem
+set_environment_variable "SOCA_BOOTSTRAP_LOGS_FOLDER" ${POST_FILESYSTEM_MOUNT_LOGS_FOLDER}
+mkdir -p ${SOCA_BOOTSTRAP_LOGS_FOLDER}
 
-# Wait until all parameters have been added to CDK
-while ! aws_cli ssm get-parameter --name "/soca/{{ context.get("/configuration/ClusterId") }}/cdk_completed" > /dev/null 2>&1; do
-    log_info "/soca/{{ context.get("/configuration/ClusterId") }}/cdk_completed not found on SSM, CDK & CloudFormation are probably still in creation, waiting a little longer"
-    sleep 120
-done
+log_info "Boostrap Asset Folder: ${SOCA_BOOTSTRAP_ASSETS_FOLDER}"
+log_info "Boostrap Logs Folder: ${SOCA_BOOTSTRAP_LOGS_FOLDER}"
 
-# Generate bootstrap script
-export SOCA_CONFIGURATION="{{ context.get("/configuration/ClusterId") }}"
-export AWS_DEFAULT_REGION="{{ context.get("/configuration/Region") }}"
+# Copy the User Data logs into the shared filesystem to simplify troubleshooting
+cp /var/log/messages ${SOCA_BOOTSTRAP_LOGS_FOLDER} || echo "/var/log/messages found on this system"
+cp /var/log/cloud-init* ${SOCA_BOOTSTRAP_LOGS_FOLDER} || echo "/var/log/cloud-init not found on this system"
+cp "${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}/*" ${SOCA_BOOTSTRAP_LOGS_FOLDER}
 
+# Generate bootstrap script and execute it
 /bin/bash /apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_manager/tools/j2generator/j2generator.sh --get-template "compute_node/02_setup.sh.j2" \
-    --output-file "${NODE_BOOTSTRAP_FOLDER}/02_setup.sh" \
+    --output-file "{{ context.get("/job/BootstrapPath") }}/02_setup.sh" \
     --ssm-key "/" \
     --add-value "KEY=/job/NodeType VALUE=login_node TYPE=str" \
     --template-dirs "/apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_node_bootstrap/"
 
-/bin/bash ${NODE_BOOTSTRAP_FOLDER}/02_setup.sh >>  ${NODE_BOOTSTRAP_FOLDER}/02_setup.sh.log 2>&1
+log_info "User Data End: $(date)"
+
+/bin/bash {{ context.get("/job/BootstrapPath") }}/02_setup.sh >> ${SOCA_BOOTSTRAP_LOGS_FOLDER}/02_setup.sh.log 2>&1
diff --git a/source/soca/cluster_node_bootstrap/compute_node/02_setup.sh.j2 b/source/soca/cluster_node_bootstrap/compute_node/02_setup.sh.j2
--- a/source/soca/cluster_node_bootstrap/compute_node/02_setup.sh.j2
+++ b/source/soca/cluster_node_bootstrap/compute_node/02_setup.sh.j2
@@ -5,55 +5,50 @@
 
 # Log Path: {{ context.get("/job/BoostrapPath") }}
 ############
-
-echo "## [BEGIN] SOCA Configuration - Do Not Delete" >> /etc/environment
-{
-  echo export "AWS_DEFAULT_REGION=\"{{ context.get("/configuration/Region") }}\""
-  echo export "SOCA_BASE_OS=\"{{ context.get("/configuration/BaseOS") }}\""
-  echo export "SOCA_NODE_TYPE=\"{{ context.get("/job/NodeType") }}\""
-  echo export "SOCA_CONFIGURATION=\"{{ context.get("/configuration/ClusterId") }}\""
-  echo export "SOCA_VERSION=\"{{ context.get("/configuration/Version") }}\""
-  echo export "DIRECTORY_AUTH_PROVIDER=\"{{ context.get("/configuration/UserDirectory/provider") }}\""
-
-} >> /etc/environment
-
-{% if context.get("/job/NodeType") == "compute_node" %}
-  {
-    echo export "SOCA_JOB_QUEUE=\"{{ context.get("/job/JobQueue") }}\""
-    echo export "SOCA_JOB_OWNER=\"{{ context.get("/job/JobOwner") }}\""
-    echo export "SOCA_JOB_NAME=\"{{ context.get("/job/JobName") }}\""
-    echo export "SOCA_JOB_PROJECT=\"{{ context.get("/job/JobProject") }}\""
-    echo export "SOCA_JOB_EFA=\"{{ context.get("/job/Efa") | lower }}\""
-    echo export "SOCA_JOB_ID=\"{{ context.get("/job/JobId") }}\""
-    echo export "SOCA_SCRATCH_SIZE=\"{{ context.get("/job/ScratchSize") }}\""
-    echo export "SOCA_FSX_LUSTRE_BUCKET=\"{{ context.get("/job/FSxLustreConfiguration").get("fsx_lustre") | lower }}\""
-    echo export "SOCA_FSX_LUSTRE_DNS=\"{{ context.get("/job/FSxLustreConfiguration").get("existing_fsx") | lower }}\""
-    echo export "SOCA_INSTANCE_HYPERTHREADING=\"{{ context.get("/job/ThreadsPerCore") }}\""
-    echo export "SOCA_SYSTEM_METRICS=\"{{ context.get("/job/SystemMetrics") | lower }}\""
-  } >> /etc/environment
-{% endif %}
-
-echo "## [END] SOCA Configuration - Do Not Delete" >> /etc/environment
-
-# Load common functions
 {% include "templates/linux/common.sh.j2" %}
 
-log_info "Stopping OpenPBS services"
-systemctl stop pbs
+log_info "Setup Start Date: $(date)"
 
-{% include "templates/linux/epel.sh.j2" %}
+# Add cache client functions (Cache CLI is automatically installed if needed)
+{% include "templates/linux/cache_client.sh.j2" %}
 
+# Adding additional SOCA Environment Variables
+set_environment_variable "SOCA_NODE_TYPE" "{{ context.get("/job/NodeType") }}"
+set_environment_variable "SOCA_VERSION" "{{ context.get("/configuration/Version") }}"
+set_environment_variable "SOCA_INSTALL_BUCKET" "{{ context.get("/configuration/S3Bucket") }}"
+
+{% if context.get("/job/NodeType") == "compute_node" %}
+  # Added via cluster_manager/orchestrator/cloudformation_builder.py
+  set_environment_variable "SOCA_JOB_QUEUE" "{{ context.get("/job/JobQueue") }}"
+  set_environment_variable "SOCA_JOB_OWNER" "{{ context.get("/job/JobOwner") }}"
+  set_environment_variable "SOCA_JOB_NAME" "{{ context.get("/job/JobName") }}"
+  set_environment_variable "SOCA_JOB_PROJECT" "{{ context.get("/job/JobProject") }}"
+  set_environment_variable "SOCA_JOB_ID" "{{ context.get("/job/JobId") }}"
+{% elif context.get("/job/NodeType") == "dcv_node" %}
+  # Added via cluster_manager/web_interface/api/v1/dcv/create_linux_desktop.py
+  set_environment_variable "SOCA_DCV_SESSION_OWNER" "{{ context.get("/dcv/SessionOwner") }}"
+  set_environment_variable "SOCA_DCV_SESSION_ID" "{{ context.get("/dcv/SessionId") }}"
+  set_environment_variable "SOCA_DCV_SESSION_NAME" "{{ context.get("/dcv/SessionName") }}"
+{% elif context.get("/job/NodeType") == "login_node" %}
+  # Add any additional variable for login nodes if needed
+{% endif %}
+
+log_info "Stopping OpenPBS services if already there"
+systemctl stop pbs || echo "PBS service not found yet, ignoring"
+
+# Install jq
 {% include "templates/linux/jq.sh.j2" %}
 
 {% set PATH = '/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/pbs/bin:/opt/pbs/sbin:/opt/pbs/bin:/apps/soca/' ~ context.get("/configuration/ClusterId") %}
 
+# Install awscliv2
 {% include "templates/linux/awscli.sh.j2" %}
 
+# Install AWS SSM Agent
 {% include "templates/linux/aws_ssm_agent.sh.j2" %}
 
-{% include "templates/linux/system_packages.sh.j2" %}
-
-{% include "templates/linux/cache_client.sh.j2" %}
+# Install Required System library/packages
+{% include "templates/linux/system_packages/install_required_packages.sh.j2" %}
 
 if [[ $(rpm -qa kernel | wc -l) -gt 1 ]]; then
     set_reboot_required "Kernel was updated during package install"
@@ -87,12 +82,11 @@ fi
 {% if context.get("/configuration/UserDirectory/provider") in ["existing_openldap", "openldap"] %}
   # OpenLDAP configuration
   {% include "templates/linux/openldap_client.sh.j2" %}
-{% elif context.get("/configuration/UserDirectory/provider") in ["existing_activedirectory","aws_ds_managed_activedirectory", "aws_ds_simple_activedirectory"] %}
+{% elif context.get("/configuration/UserDirectory/provider") in ["existing_active_directory","aws_ds_managed_activedirectory", "aws_ds_simple_activedirectory"] %}
   # Active Directory configuration
   {% include "templates/linux/join_activedirectory.sh.j2" %}
 {% else %}
-  log_error "UserDirectory/provider must be existing_activedirectory, existing_openldap, openldap, aws_ds_simple_activedirectory, aws_ds_managed_activedirectory, detected {{ context.get("/configuration/UserDirectory/provider") }}"
-  exit 1
+  exit_fail "UserDirectory/provider must be existing_active_directory, existing_openldap, openldap, aws_ds_simple_activedirectory, aws_ds_managed_activedirectory, detected {{ context.get("/configuration/UserDirectory/provider") }}"
 {% endif %}
 
 # Disable StrictHostKeyChecking
@@ -110,16 +104,20 @@ fi
 # Tag Network Interface for the Compute Node
 {% include "templates/linux/tags/eni.sh.j2" %}
 
+log_info "Setup End Date: $(date)"
+
 # Prepare crontab for post-reboot or execute the post-reboot script automatically
 REBOOT_REQUIRED=$(get_reboot_required)
 {% if context.get("/job/NodeType") in ("dcv_node", "compute_node") %}
 if [[ "${REBOOT_REQUIRED}" == "yes" ]]; then
-  echo "@reboot /bin/bash "{{ context.get('/job/BootstrapPath') }}/03_setup_post_reboot.sh" >> {{ context.get('/job/BootstrapPath') }}/$(hostname -s)/03_setup_post_reboot.log 2>&1" | crontab -
+  echo "@reboot /bin/bash "{{ context.get('/job/BootstrapPath') }}/03_setup_post_reboot.sh" >> ${SOCA_BOOTSTRAP_LOGS_FOLDER}/03_setup_post_reboot.log 2>&1" | crontab -
+  log_info "Final bootstrap sequence will be executed post reboot, verifying crontab"
+  crontab -l
   log_info "Rebooting the machine"
   reboot
 else
   log_info "No reboot needed, continuing bootstrap sequence"
-  /bin/bash "{{ context.get('/job/BootstrapPath') }}/03_setup_post_reboot.sh" >> {{ context.get('/job/BootstrapPath') }}/$(hostname -s)/03_setup_post_reboot.log 2>&1
+  /bin/bash "{{ context.get('/job/BootstrapPath') }}/03_setup_post_reboot.sh" >> ${SOCA_BOOTSTRAP_LOGS_FOLDER}/03_setup_post_reboot.log 2>&1
 fi
 {% else %}
  log_info "No post_reboot customizations for login_nodes or controller host"
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/common/log.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/common/log.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/common/log.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/common/log.sh.j2
@@ -2,24 +2,49 @@
 # SPDX-License-Identifier: Apache-2.0
 
 # Begin: Log Functions. Added via common.j2
+function log_debug() {
+  log_wrapper "DEBUG" "${@}"
+}
+
 function log_info() {
-  echo "[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [INFO] ${@}"
+  log_wrapper "INFO" "${@}"
 }
 
 function log_warning() {
-  echo "[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [WARNING] ${@}"
+  log_wrapper "WARNING" "${@}"
 }
 
 function log_error() {
-  echo "[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [ERROR] ${@}"
-}
-
-function log_debug() {
-  echo "[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [DEBUG] ${@}"
+  log_wrapper "ERROR" "${@}"
 }
 
 function exit_fail () {
-   echo "[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [FATAL] ${@}"
+  log_wrapper "FATAL" "${@}"
   exit 1
+}
+
+function log_wrapper() {
+  # To avoid issue with native echo and log_info in function (both write to stdout), we are redirecting log_info to stderr
+  # we use echo to return function output from specific functions
+  local LOG_LEVEL="$1"
+  shift
+  local VALID_LOG_LEVELS=("INFO" "DEBUG" "WARNING" "ERROR" "FATAL")
+  if [[ ! "${VALID_LOG_LEVELS[*]}" =~ "${LOG_LEVEL}" ]]; then
+    echo "[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [INVALID] Invalid log level: ${LOG_LEVEL}, Call log_debug log_info log_warning log_error or exit_fail directly." >&2
+    exit 1
+  fi
+
+  local LOG_MESSAGE="[$(date +"%Y-%m-%d %H:%M:%S,%3N")] [${LOG_LEVEL}] ${@}"
+  if [[ -n "${SOCA_BOOTSTRAP_LOGS_FOLDER}" ]] && [[ -d "${SOCA_BOOTSTRAP_LOGS_FOLDER}" ]]; then
+    # Keep track of warning/fatal/error on stdout as well as separate files
+    if [[ ${LOG_LEVEL} == "WARNING" ]] || [[ ${LOG_LEVEL} == "FATAL" ]] || [[ ${LOG_LEVEL} == "ERROR" ]]; then
+      echo "${LOG_MESSAGE}" | tee -a "${SOCA_BOOTSTRAP_LOGS_FOLDER}/bootstrap_${LOG_LEVEL}.log" >&2
+    else
+      echo "${LOG_MESSAGE}" >&2
+    fi
+  else
+    # Handle case where SOCA_BOOTSTRAP_LOGS_FOLDER is not set
+    echo "${LOG_MESSAGE}" >&2
+  fi
 }
 # End: Log Functions
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/dcv/dcv_server.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/dcv/dcv_server.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/dcv/dcv_server.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/dcv/dcv_server.sh.j2
@@ -29,55 +29,52 @@ function install_dcv_server () {
   if [[ ${MACHINE} == "x86_64" ]]; then
     local DCV_URL="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/x86_64/url") }}"
     local DCV_HASH="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/x86_64/sha256") }}"
-    local DCV_TGZ="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/x86_64/tgz") }}"
     local DCV_VERSION="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/x86_64/version") }}"
   elif [[ ${MACHINE} == "aarch64" ]]; then
     local DCV_URL="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/aarch64/url") }}"
     local DCV_HASH="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/aarch64/sha256") }}"
-    local DCV_TGZ="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/aarch64/tgz") }}"
     local DCV_VERSION="{{ context.get("/system/dcv/" ~ DCV_VERSION_FAMILY ~ "/aarch64/version") }}"
   else
-    exit_fail "Unrecognized machine type. Must be either x86_64 or aarch64"
+    exit_fail "Unrecognized machine type. Virtual Machine must be either x86_64 or aarch64, detected ${MACHINE}"
   fi
 
   log_info "Detected following DCV download information:"
   log_info "DCV_URL ${DCV_URL}"
   log_info "DCV_HASH ${DCV_HASH}"
-  log_info "DCV_TGZ ${DCV_TGZ}"
   log_info "DCV_VERSION ${DCV_VERSION}"
 
-  # Download and Install DCV
-  mkdir -p /root/soca_bootstrap/dcvserver
-  pushd /root/soca_bootstrap/dcvserver
-  log_info "Downloading DCV ..."
-  wget ${DCV_URL}
-  if [[ $(sha256sum ${DCV_TGZ} | awk '{print $1}') != ${DCV_HASH} ]];  then
-     exit_fail "Checksum for DCV failed. File may be compromised."
-  fi
+  mkdir -p "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/dcvserver"
+  pushd "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/dcvserver"
 
-  log_info "Extracting DCV archive ..."
-  tar zxvf ${DCV_TGZ}
-  cd nice-dcv-${DCV_VERSION}
+  # Download and Install DCV (if not already there)
+  if ! verify_package_installed "nice-dcv-server" && ! verify_package_installed "amazon-dcv-server"; then
+    log_info "DCV Not found, Downloading + Installing DCV ..."
+    file_download --download-url="${DCV_URL}" --save-as="dcv_installer_${DCV_VERSION}.tgz" --sha256-checksum="${DCV_HASH}"
 
-  log_info "Installing DCV ..."
+    log_info "Extracting DCV archive ..."
+    tar zxvf "dcv_installer_${DCV_VERSION}.tgz" --strip-components=1 -C .
 
-  rpm -ivh nice-xdcv-*.${MACHINE}.rpm --nodeps
-  rpm -ivh nice-dcv-server-*.${MACHINE}.rpm --nodeps
-  rpm -ivh nice-dcv-web-viewer-*.${MACHINE}.rpm --nodeps
+    log_info "Installing DCV ..."
 
-  log_info "Enable DCV support for USB remotization .. "
-  packages_install dkms
-  DCVUSBDRIVERINSTALLER=$(which dcvusbdriverinstaller)
-  $DCVUSBDRIVERINSTALLER --quiet
+    rpm -ivh nice-xdcv-*.${MACHINE}.rpm --nodeps
+    rpm -ivh nice-dcv-server-*.${MACHINE}.rpm --nodeps
+    rpm -ivh nice-dcv-web-viewer-*.${MACHINE}.rpm --nodeps
 
-  # Enable GPU support
-  if [[ -n ${GPU_DETECTED} ]]; then
-    log_info "Detected GPU instance, adding support for nice-dcv-gl"
-    rpm -ivh nice-dcv-gl*.rpm --nodeps
+    log_info "Enable DCV support for USB remotization .. "
+    packages_install dkms
+    DCVUSBDRIVERINSTALLER=$(which dcvusbdriverinstaller)
+    $DCVUSBDRIVERINSTALLER --quiet
+
+    # Enable GPU support
+    if [[ -n ${GPU_DETECTED} ]]; then
+      log_info "Detected GPU instance, adding support for nice-dcv-gl"
+      rpm -ivh nice-dcv-gl*.rpm --nodeps
+    fi
+  else
+    log_info "DCV already up and running on this machine, skipping DCV install"
   fi
 
   # Configure DCV
-  mv /etc/dcv/dcv.conf /etc/dcv/dcv.conf.orig
   local IDLE_TIMEOUT={{ context.get("/system/dcv/idle_timeout") }}
   local USER_HOME=$(eval echo ~${DCV_SESSION_OWNER})
   local DCV_STORAGE_ROOT="$USER_HOME/{{ context.get("/system/dcv/session_storage") }}" # Create the storage root location if needed
@@ -86,6 +83,7 @@ function install_dcv_server () {
   mkdir -p ${DCV_STORAGE_ROOT}
   chown ${DCV_SESSION_OWNER} ${DCV_STORAGE_ROOT}
 
+  mv /etc/dcv/dcv.conf /etc/dcv/dcv.conf.original.$(date +%s)
   echo -e """
 [license]
 [log]
@@ -107,6 +105,7 @@ os-auto-lock=false
 """ > /etc/dcv/dcv.conf
 
   log_info "Disabling X11 DPMS"
+  cp /etc/X11/xorg.conf.d/99-disable-dpms.conf /etc/X11/xorg.conf.d/99-disable-dpms.conf.original.$(date +%s) || echo "/etc/X11/xorg.conf.d/99-disable-dpms.conf not found, file will be created"
   echo -e """
 Section \"Extensions\"
     Option      \"DPMS\" \"Disable\"
@@ -121,7 +120,17 @@ EndSection""" > /etc/X11/xorg.conf.d/99-disable-dpms.conf
   systemctl isolate multi-user.target
   systemctl isolate graphical.target
 
-  log_info "Creating SOCA DCV Service to start/stop DCV session via socadcv "
+  log_info "Creating SOCA DCV Service to start/stop DCV session via socadcv"
+
+  if [[ -f "/etc/systemd/system/socadcv.service" ]]; then
+    log_info "/etc/systemd/system/socadcv.service already exist, probably from a previous configuration, removing it and creating a new one"
+    systemctl stop socadcv.service || echo "Stopping socadcv.service not needed"
+    systemctl disable socadcv.service || echo "Disabling socadcv.service not needed"
+    rm -f /etc/systemd/system/socadcv.service
+    systemctl daemon-reload
+    systemctl reset-failed socadcv.service || echo "reset-failed socadcv.service not needed"
+  fi
+
   echo -e "
 [Unit]
 Description=SOCA DCV Setup Service
@@ -141,7 +150,7 @@ WantedBy=multi-user.target" > /etc/systemd/system/socadcv.service
   systemctl enable socadcv
 
   log_info "Launching DCV session dcv create-session --user ${DCV_SESSION_OWNER} --owner ${DCV_SESSION_OWNER} --type virtual --storage-root ${DCV_STORAGE_ROOT} ${DCV_SESSION_ID}"
-   systemctl start socadcv
+  systemctl start socadcv
 
   log_info "Stopping Firewall if needed"
   systemctl stop firewalld
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_lustre.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_lustre.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_lustre.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_lustre.sh.j2
@@ -2,139 +2,189 @@
 # SPDX-License-Identifier: Apache-2.0
 
 # Begin: Mount FSx Lustre
-{% if context.get("/configuration/BaseOS") in ("amazonlinux2", "amazonlinux2023", "centos7", "rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
+{% if "templates/linux/shared_storage/mount_fsx_lustre.sh.j2" not in ns.template_already_included %}
+  {% set _ = ns.template_already_included.append("templates/linux/shared_storage/mount_fsx_lustre.sh.j2") %}
 
-{% if "templates/linux/shared_storage/mount_fsx_lustre.sh.j2" not in included_templates %}
-   {% if included_templates is not defined %}
-     # Ensure function is only included once
-      {% set included_templates = ["templates/linux/shared_storage/mount_fsx_lustre.sh.j2"] %}
-   {% else %}
-      {% set included_templates = included_templates + ["templates/linux/shared_storage/mount_fsx_lustre.sh.j2"] %}
-   {% endif %}
+  {% include "templates/linux/shared_storage/fstab_wrapper.sh.j2" %}
 
-{% if context.get("/configuration/BaseOS") in ("rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
-function rhel_driver_install {
-  log_info "Installing FSx Lustre Driver for RHEL based distro"
-  local EL_VERSION=${1}
-  local REPO_VERSION_REWRITE=${2}
+  {% if context.get("/configuration/BaseOS") in ("rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
+    function rhel_driver_install {
+      log_info "Installing FSx Lustre Driver for RHEL based distro"
+      local EL_VERSION=${1}
+      local REPO_VERSION_REWRITE=${2}
 
-  if [[ ! ${EL_VERSION} =~ ^(7|8|9)$ ]]; then
-    log_error "EL Version must be either 7, 8 or 9"
-  else
-    log_info "Getting FSx Lustre repo for RHEL distros version ${EL_VERSION}"
-    wget https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-rpm-public-key.asc -O /tmp/fsx-rpm-public-key.asc
-    {% if context.get("/configuration/BaseOS") in ("centos7", "rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
-    rpm --import /tmp/fsx-rpm-public-key.asc
-    {% endif %}
-    wget https://fsx-lustre-client-repo.s3.amazonaws.com/el/"${EL_VERSION}"/fsx-lustre-client.repo -O /etc/yum.repos.d/aws-fsx.repo
-
-    if [[ -n "${REPO_VERSION_REWRITE}" ]]; then
-      echo "SED Rewrite enabled {$REPO_VERSION_REWRITE}"
-      sed -i "${REPO_VERSION_REWRITE}" /etc/yum.repos.d/aws-fsx.repo
-    fi
-
-    packages_clean
-    packages_install kmod-lustre-client lustre-client
-  fi
-  log_info "FSx Driver installed"
-}
-{% endif %}
-
-function mount_fsx_lustre {
-  log_info "Preparing FSx Lustre mount"
-  local ENDPOINT="${1}" # FSxL DNS
-  local MOUNT_POINT="${2}" # Local linux folder to use as mount point
-  local FSX_ID=$(echo "${ENDPOINT}" | cut -d. -f1)
-  local KERNEL=$(uname -r)
-  local MACHINE=$(uname -m)
-
-  for ((LIFECYCLE_VERIFICATION=1; LIFECYCLE_VERIFICATION<=30; LIFECYCLE_VERIFICATION++)); do
-      log_info "Verifying if ${FSX_ID} is in AVAILABLE state ..."
-      if [[ $(aws_cli fsx describe-file-systems --file-system-ids "${FSX_ID}" --query FileSystems[].Lifecycle --output text) == "AVAILABLE" ]]; then
-        break
+      if [[ ! ${EL_VERSION} =~ ^(7|8|9)$ ]]; then
+        log_error "EL Version must be either 7, 8 or 9"
       else
-        log_error "FSx Lustre Not available yet .. trying again in 60 seconds, attempt ${LIFECYCLE_VERIFICATION}"
+        log_info "Getting FSx Lustre repo for RHEL distros version ${EL_VERSION}"
+
+        file_download --download-url="https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-rpm-public-key.asc" --save-as="${SOCA_BOOTSTRAP_ASSETS_FOLDER}/fsx-rpm-public-key.asc"
+
+        if [[ ! -f "/etc/yum.repos.d/aws-fsx.repo" ]]; then
+          log_info "Downloading https://fsx-lustre-client-repo.s3.amazonaws.com/el/${EL_VERSION}/fsx-lustre-client.repo and saving it to /etc/yum.repos.d/aws-fsx.repo"
+          file_download --download-url="https://fsx-lustre-client-repo.s3.amazonaws.com/el/"${EL_VERSION}"/fsx-lustre-client.repo" --save-as="/etc/yum.repos.d/aws-fsx.repo"
+        fi
+
+        if [[ -n "${REPO_VERSION_REWRITE}" ]]; then
+          echo "SED Rewrite enabled ${REPO_VERSION_REWRITE}"
+          sed -i "${REPO_VERSION_REWRITE}" /etc/yum.repos.d/aws-fsx.repo
+        fi
+
+        packages_clean
+        if [[ ! -f "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/fsx-rpm-public-key.asc" ]]; then
+          log_warning "Unable to locate ${SOCA_BOOTSTRAP_ASSETS_FOLDER}/fsx-rpm-public-key.asc, installing without gpgcheck"
+          packages_install kmod-lustre-client lustre-client --nogpgcheck
+        else
+          {% if context.get("/configuration/BaseOS") in ("centos7", "rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
+            rpm --import "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/fsx-rpm-public-key.asc"
+          {% endif %}
+          packages_install kmod-lustre-client lustre-client
+        fi
+
       fi
-      if [[ ${LIFECYCLE_VERIFICATION} -eq 30 ]]; then
-          exit_fail "Unable to determine if the filesystem is in AVAILABLE state after 30 attempts. Exiting."
-      fi
-      sleep 60
+      log_info "FSx Driver installed"
+    }
+  {% endif %}
+
+  function mount_fsx_lustre {
+    log_info "Preparing FSx Lustre mount"
+    # MOUNT_TARGET (required): FSx for Lustre Filesystem ID. Used to determine actual mount endpoint if ENDPOINT is not set
+    # MOUNT_PATH (required): Unix path to mount the EFS on
+    # ON_MOUNT_FAILURE (required): What to do if the mount is not successful (exit or ignore)
+    # MOUNT_OPTIONS (optional): NFS options to use
+    # ENABLED (optional): Whether the automount is enabled
+
+    for arg in "$@"; do
+        case $arg in
+            --mount-target=*) MOUNT_TARGET="${arg#*=}" ;;
+            --mount-path=*) MOUNT_PATH="${arg#*=}" ;;
+            --mount-options=*) MOUNT_OPTIONS="${arg#*=}" ;;
+            --on-mount-failure=*) ON_MOUNT_FAILURE="${arg#*=}" ;;
+            --enabled=*) ENABLED="${arg#*=}" ;;
+            *) exit_fail "Unknown arg ${arg} for mount_efs";;
+        esac
     done
 
-  if [[ "${ENDPOINT}" == *"@tcp:/"* ]]; then
-    log_info "FSX Mount Name already specified"
-  else
-    log_info "FSX Mount Name not specified, trying to retrieve it"
-    ENDPOINT+="@tcp:/$(aws_cli fsx describe-file-systems --file-system-ids "${FSX_ID}" --query FileSystems[].LustreConfiguration.MountName --output text)"
-  fi
-
-  log_info "Mount endpoint: ${ENDPOINT}"
-
-  if grep -qF "${ENDPOINT} ${MOUNT_POINT}" /etc/fstab; then
-    log_error "This entry seems to already exist on /etc/fstab, skipping it"
-    echo -n "success"
-    return
-  fi
-
-  if mount | grep -q "${MOUNT_POINT}"; then
-    log_error "${MOUNT_POINT} is already mounted to a different disk"
-    exit_fail
-  fi
-
-  log_info "Creating ${MOUNT_POINT} if it does not exist"
-  mkdir -p ${MOUNT_POINT}
-
-  log_info "Preparing to install Lustre driver on kernel version: ${KERNEL} running on: ${MACHINE}"
-  if ! verify_package_installed lustre-client; then
-    # Install FSx for Lustre Client
-    # https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html
-    log_info "FSx Lustre Client not installed, installing it .. "
-    {% if context.get("/configuration/BaseOS") == "amazonlinux2" %}
-      amazon-linux-extras install -y lustre
-    {% elif context.get("/configuration/BaseOS") == "amazonlinux2023" %}
-      packages_install lustre-client
-    {% elif context.get("/configuration/BaseOS") in ("rhel7", "centos7") %}
-      case "$KERNEL$MACHINE" in
-        *"3.10.0-957"*)
-          packages_install https://downloads.whamcloud.com/public/lustre/lustre-2.10.8/el7/client/RPMS/x86_64/kmod-lustre-client-2.10.8-1.el7.x86_64.rpm
-          packages_install https://downloads.whamcloud.com/public/lustre/lustre-2.10.8/el7/client/RPMS/x86_64/lustre-client-2.10.8-1.el7.x86_64.rpm;;
-        *"3.10.0-1062"*) rhel_driver_install 7 "s#7#7.7#" ;;
-        *"3.10.0-1127"*) rhel_driver_install 7 "s#7#7.8#" ;;
-        *"3.10.0-1160"*) rhel_driver_install 7 ;;
-        *"4.18.0-193"*)  rhel_driver_install 7 ;;
-        *) log_error "ERROR: Can't install FSx for Lustre client as kernel version: ${KERNEL} isn't matching expected versions for EL7" ;;
-      esac
-
-    {% elif context.get("/configuration/BaseOS") in ("rhel8", "rocky8") %}
-        case "$KERNEL$MACHINE" in
-          *"4.18.0-553"*) rhel_driver_install 8 ;;
-          *"4.18.0-513"*) rhel_driver_install 8 's#8#8.9#' ;;
-          *"4.18.0-477"*) rhel_driver_install 8 's#8#8.8#' ;;
-          *"4.18.0-425"*) rhel_driver_install 8 's#8#8.7#' ;;
-          *"4.18.0-372"*) rhel_driver_install 8 's#8#8.6#' ;;
-          *"4.18.0-348"*) rhel_driver_install 8 's#8#8.5#' ;;
-          *"4.18.0-305"*) rhel_driver_install 8 's#8#8.4#' ;;
-          *"4.18.0-240"*) rhel_driver_install 8 's#8#8.3#' ;;
-          *"4.18.0-193"*) rhel_driver_install 8 's#8#8.2#' ;;
-          *) log_error "Can't install FSx for Lustre client as kernel version $KERNEL isn't matching expected versions for EL8"
-            ;;
-        esac
-
-    {% elif context.get("/configuration/BaseOS") in ("rhel9", "rocky9") %}
-        case "$KERNEL$MACHINE" in
-          *"5.14.0-427"*) rhel_driver_install 9 ;;
-          *"5.14.0-362"*) rhel_driver_install 9 's#9#9.3#' ;;
-          *"5.14.0-70"*) rhel_driver_install 9 's#9#9.0#' ;;
-          *) log_error "Can't install FSx for Lustre client as kernel version $KERNEL isn't matching expected versions for EL9";;
-        esac
-    {% endif %}
-    else
-      log_info "FSx Lustre Driver already installed ..."
+    if [[ -z "${ENABLED}" ]]; then
+      ENABLED="true"
+      log_warning "--enabled not set, default to ${ENABLED}"
     fi
 
-    echo "${ENDPOINT} ${MOUNT_POINT} lustre defaults,noatime,flock,_netdev 0 0" >> /etc/fstab
-    log_info "Completed FSx Lustre mount for ${ENDPOINT} on ${MOUNT_POINT}"
-}
-{% endif %}
+    if [[ -z "${MOUNT_PATH}" ]]; then
+      exit_fail "--mount-path not set for mount_fsx_lustre"
+    fi
+
+    if [[ -z "${ON_MOUNT_FAILURE}" ]]; then
+      ON_MOUNT_FAILURE="ignore"
+      log_warning "--on-mount-failure not specified, default to ${ON_MOUNT_FAILURE}"
+    fi
+
+    if [[ -z "${MOUNT_OPTIONS}" ]]; then
+      MOUNT_OPTIONS="defaults,noatime,flock,_netdev"
+      log_warning "--mount-options not specified, default to ${ON_MOUNT_FAILURE}"
+    fi
+
+    if ! verify_package_installed jq; then
+      log_info "jq not found, installing it ..."
+      packages_install jq
+    fi
+
+    if [[ -z "${MOUNT_TARGET}" ]]; then
+      exit_fail "--mount-target not set for mount_fsx_lustre"
+    fi
+
+    if [[ "${ENABLED}" == "true" ]]; then
+
+      local FSX_LUSTRE_INFO=$(aws_cli fsx describe-file-systems --file-system-ids "${MOUNT_TARGET}")
+      local FSX_LUSTRE_DNS=$(echo ${FSX_LUSTRE_INFO} | jq -r '.FileSystems[].DNSName // "NO_VALUE"')
+      local FSX_LUSTRE_MOUNT_NAME=$(echo ${FSX_LUSTRE_INFO} | jq -r '.FileSystems[].LustreConfiguration.MountName // "NO_VALUE"')
+
+      if [[ -z ${FSX_LUSTRE_DNS} ]]; then
+        exit_fail "Unable to determine DNSName for ${MOUNT_TARGET}"
+      fi
+
+      if [[ -z ${FSX_LUSTRE_MOUNT_NAME} ]]; then
+        exit_fail "Unable to determine MountName for ${MOUNT_TARGET}"
+      fi
+
+      local ENDPOINT="${FSX_LUSTRE_DNS}@tcp:/${FSX_LUSTRE_MOUNT_NAME}"
+      local KERNEL=$(uname -r)
+      local MACHINE=$(uname -m)
+
+      for ((LIFECYCLE_VERIFICATION=1; LIFECYCLE_VERIFICATION<=30; LIFECYCLE_VERIFICATION++)); do
+          log_info "Verifying if ${MOUNT_TARGET} is in AVAILABLE state ..."
+          if [[ $(aws_cli fsx describe-file-systems --file-system-ids "${MOUNT_TARGET}" --query FileSystems[].Lifecycle --output text) == "AVAILABLE" ]]; then
+            break
+          else
+            log_warning "FSx Lustre Not available yet .. trying again in 60 seconds, attempt ${LIFECYCLE_VERIFICATION}"
+          fi
+          if [[ ${LIFECYCLE_VERIFICATION} -eq 30 ]]; then
+              exit_fail "Unable to determine if the filesystem is in AVAILABLE state after 30 attempts. Exiting."
+          fi
+          sleep 60
+        done
+
+      log_info "Preparing to install Lustre driver on kernel version: ${KERNEL} running on: ${MACHINE}"
+      if ! verify_package_installed lustre-client; then
+        # Install FSx for Lustre Client
+        # https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html
+        log_info "FSx Lustre Client not installed, installing it .. "
+        {% if context.get("/configuration/BaseOS") == "amazonlinux2" %}
+          amazon-linux-extras install -y lustre
+        {% elif context.get("/configuration/BaseOS") == "amazonlinux2023" %}
+          packages_install lustre-client
+        {% elif context.get("/configuration/BaseOS") in ("rhel7", "centos7") %}
+          case "$KERNEL$MACHINE" in
+            *"3.10.0-957"*)
+              packages_install https://downloads.whamcloud.com/public/lustre/lustre-2.10.8/el7/client/RPMS/x86_64/kmod-lustre-client-2.10.8-1.el7.x86_64.rpm
+              packages_install https://downloads.whamcloud.com/public/lustre/lustre-2.10.8/el7/client/RPMS/x86_64/lustre-client-2.10.8-1.el7.x86_64.rpm;;
+            *"3.10.0-1062"*) rhel_driver_install 7 "s#7#7.7#" ;;
+            *"3.10.0-1127"*) rhel_driver_install 7 "s#7#7.8#" ;;
+            *"3.10.0-1160"*) rhel_driver_install 7 ;;
+            *"4.18.0-193"*)  rhel_driver_install 7 ;;
+            *) log_error "ERROR: Can't install FSx for Lustre client as kernel version: ${KERNEL} isn't matching expected versions for EL7" ;;
+          esac
+
+        {% elif context.get("/configuration/BaseOS") in ("rhel8", "rocky8") %}
+            case "$KERNEL$MACHINE" in
+              *"4.18.0-553"*) rhel_driver_install 8 ;;
+              *"4.18.0-513"*) rhel_driver_install 8 's#8#8.9#' ;;
+              *"4.18.0-477"*) rhel_driver_install 8 's#8#8.8#' ;;
+              *"4.18.0-425"*) rhel_driver_install 8 's#8#8.7#' ;;
+              *"4.18.0-372"*) rhel_driver_install 8 's#8#8.6#' ;;
+              *"4.18.0-348"*) rhel_driver_install 8 's#8#8.5#' ;;
+              *"4.18.0-305"*) rhel_driver_install 8 's#8#8.4#' ;;
+              *"4.18.0-240"*) rhel_driver_install 8 's#8#8.3#' ;;
+              *"4.18.0-193"*) rhel_driver_install 8 's#8#8.2#' ;;
+              *) log_error "Can't install FSx for Lustre client as kernel version $KERNEL isn't matching expected versions for EL8"
+                ;;
+            esac
+
+        {% elif context.get("/configuration/BaseOS") in ("rhel9", "rocky9") %}
+            case "$KERNEL$MACHINE" in
+              *"5.14.0-503"*) rhel_driver_install 9 ;;
+              *"5.14.0-427"*) rhel_driver_install 9 's#9#9.4#' ;;
+              *"5.14.0-362"*) rhel_driver_install 9 's#9#9.3#' ;;
+              *"5.14.0-70"*) rhel_driver_install 9 's#9#9.0#' ;;
+              *) log_error "Can't install FSx for Lustre client as kernel version $KERNEL isn't matching expected versions for EL9";;
+            esac
+        {% endif %}
+      else
+        log_info "FSx Lustre Driver already installed ..."
+      fi
+
+      if fstab_wrapper "${ENDPOINT} ${MOUNT_PATH} lustre ${MOUNT_OPTIONS} 0 0"; then
+        log_info "Successfully mounted ${ENDPOINT} as ${MOUNT_PATH}"
+      else
+        if [[ ${ON_MOUNT_FAILURE} == "exit" ]]; then
+          exit_fail "Unable to mount ${ENDPOINT} as ${MOUNT_PATH}"
+        else
+          log_warning "Unable to mount ${ENDPOINT} as ${MOUNT_PATH}, ignoring"
+        fi
+      fi
+    else
+      log_warning "FSx Lustre Filesystem ${MOUNT_TARGET}, mount path ${MOUNT_PATH} is not enabled. Skipping ... Detected enabled flag ${ENABLED}"
+    fi
+    }
 {% endif %}
 # End: Mount FSx Lustre
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_ontap.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_ontap.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_ontap.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/shared_storage/mount_fsx_ontap.sh.j2
@@ -2,27 +2,134 @@
 # SPDX-License-Identifier: Apache-2.0
 
 # Begin: FSx OnTap
-{% if context.get("/configuration/BaseOS") in ("amazonlinux2", "amazonlinux2023", "centos7", "rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
 
-{% include "templates/linux/shared_storage/nfs_wrapper.sh.j2" %}
+{% if "templates/linux/shared_storage/mount_fsx_ontap.sh.j2" not in ns.template_already_included %}
+  {% set _ = ns.template_already_included.append("templates/linux/shared_storage/mount_fsx_ontap.sh.j2") %}
 
-function mount_fsx_ontap () {
-  local ENDPOINT="${1}"
-  local MOUNT_POINT="${2}" # Local linux folder to use as mountpoint
-  local GET_FSX_MOUNT_PATH=$(echo "${ENDPOINT}" | cut -d":" -f2)
-  if [[ -z ${GET_FSX_MOUNT_PATH} ]]; then
-    log_info "FSx OnTap Junction Path  not specified, trying to retrieve it"
-    GET_FSX_MOUNT_NAME=$(aws_cli fsx describe-file-systems --file-system-ids "${FSX_ID}" --query FileSystems[].OntapConfiguration.JunctionPath --output text)
-    log_info "FSx OnTap Junction Path: ${GET_FSX_MOUNT_PATH}"
-    ENDPOINT+=":${GET_FSX_MOUNT_PATH}"
-  fi
-  local NFS_OPTS_DATA="nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
-  if wrapper_mount_nfs ${ENDPOINT} ${MOUNT_POINT} ${NFS_OPTS_DATA} == "success"; then
-    log_info "Successfully mounted ${ENDPOINT} as ${MOUNT_POINT}"
-  else
-    log_error "Unable to mount  ${ENDPOINT} as ${MOUNT_POINT}"
-    exit_fail
-  fi
-}
+  {% include "templates/linux/shared_storage/fstab_wrapper.sh.j2" %}
+
+  function mount_fsx_ontap () {
+
+    # MOUNT_TARGET (required): FSxN Volume ID. Used to determine actual mount endpoint if ENDPOINT is not set
+    # MOUNT_PATH (required): Unix path to mount the the filesystem on
+    # ON_MOUNT_FAILURE (required): What to do if the mount is not successful (exit or ignore)
+    # MOUNT_OPTIONS (optional): NFS options to use
+    # ENABLED (optional): Whether the automount is enabled
+
+    local MOUNT_TARGET
+    local MOUNT_PATH
+    local MOUNT_OPTIONS
+    local ON_MOUNT_FAILURE
+    for arg in "$@"; do
+        case $arg in
+            --mount-target=*) MOUNT_TARGET="${arg#*=}" ;;
+            --mount-path=*) MOUNT_PATH="${arg#*=}" ;;
+            --mount-options=*) MOUNT_OPTIONS="${arg#*=}" ;;
+            --on-mount-failure=*) ON_MOUNT_FAILURE="${arg#*=}" ;;
+            --enabled=*) ENABLED="${arg#*=}" ;;
+            *) exit_fail "Unknown arg ${arg} for mount_efs";;
+        esac
+    done
+
+    if ! verify_package_installed jq; then
+      log_info "jq not found, installing it ..."
+      packages_install jq
+    fi
+
+    if [[ -z "${ENABLED}" ]]; then
+      ENABLED="true"
+      log_warning "--enabled not set, default to ${ENABLED}"
+    fi
+
+    if [[ -z "${MOUNT_PATH}" ]]; then
+      exit_fail "--mount-path not set for mount_fsx_ontap"
+    fi
+
+    if [[ -z "${ON_MOUNT_FAILURE}" ]]; then
+      ON_MOUNT_FAILURE="ignore"
+      log_warning "--on-mount-failure not specified, default to ${ON_MOUNT_FAILURE}"
+    fi
+
+    if [[ -z "${MOUNT_TARGET}" ]]; then
+      exit_fail "--mount-target not set for mount_fsx_ontap"
+    fi
+
+    if [[ -z "${MOUNT_OPTIONS}" ]]; then
+      # Note: mounting via nfsv4 without idmapd configuration will cause group membership to break and default to nobody
+      MOUNT_OPTIONS="defaults,noatime,_netdev"
+      log_warning "--mount-options not set, default to ${MOUNT_OPTIONS}"
+    fi
+
+    if [[ "${ENABLED}" == "true" ]]; then
+      # Retrieve FSx ONTAP Volume info
+      local FSX_DESCRIBE_VOLUME=$(aws_cli fsx describe-volumes --volume-ids ${MOUNT_TARGET})
+      local FSX_VOLUME_SVM_ID=$(echo ${FSX_DESCRIBE_VOLUME} | jq -r '.Volumes[].OntapConfiguration.StorageVirtualMachineId // "NO_VALUE"')
+      local FSX_VOLUME_JUNCTION_PATH=$(echo ${FSX_DESCRIBE_VOLUME} | jq -r '.Volumes[].OntapConfiguration.JunctionPath // "NO_VALUE"')
+      local FSX_VOLUME_RESOURCE_ARN=$(echo ${FSX_DESCRIBE_VOLUME} | jq -r '.Volumes[].ResourceARN // "NO_VALUE"')
+
+      if [[ "${FSX_VOLUME_SVM_ID}" == "NO_VALUE" ]] || [[ "${FSX_VOLUME_JUNCTION_PATH}" == "NO_VALUE" ]] || [[ "${FSX_VOLUME_RESOURCE_ARN}" == "NO_VALUE" ]]; then
+        exit_fail "Unable to verify required FSx Volume Information for ${MOUNT_TARGET} : FSX_VOLUME_RESOURCE_ARN = ${FSX_VOLUME_RESOURCE_ARN}, FSX_VOLUME_SVM_ID=${FSX_VOLUME_SVM_ID}, FSX_VOLUME_JUNCTION_PATH=${FSX_VOLUME_JUNCTION_PATH}. API Result ${FSX_DESCRIBE_VOLUME}"
+      fi
+
+      # Retrieve FSx ONTAP SVM info
+      local FSX_DESCRIBE_SVM=$(aws_cli fsx describe-storage-virtual-machines --storage-virtual-machine-ids ${FSX_VOLUME_SVM_ID})
+      if [[ ${FSX_VOLUME_SVM_ID} == "NO_VALUE" ]]; then
+        exit_fail "Unable to determine SVM ID for FSX Volume ${MOUNT_TARGET}. API Result ${FSX_DESCRIBE_SVM}"
+      else
+        local NFS_DNS_NAME=$(echo ${FSX_DESCRIBE_SVM} | jq -r '.StorageVirtualMachines[].Endpoints.Nfs.DNSName // "NO_VALUE"' )
+        if [[ ${NFS_DNS_NAME} == "NO_VALUE" ]]; then
+          exit_fail "Unable to determine StorageVirtualMachines[].Endpoints.Nfs.DNSName for ${FSX_VOLUME_SVM_ID}. API Result ${FSX_DESCRIBE_SVM}"
+        fi
+
+        local DS_DOMAIN_NAME=$(echo ${FSX_DESCRIBE_SVM} | jq -r '.StorageVirtualMachines[0].ActiveDirectoryConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName // "NO_VALUE"')
+        if [[ ${DS_DOMAIN_NAME} == "NO_VALUE" ]]; then
+          log_warning "Unable to determine AD Domain Name for ${FSX_VOLUME_SVM_ID}, group membership may default to nobody. API Result ${FSX_DESCRIBE_SVM}"
+        else
+           log_info "Updating idmap.conf to support correct AD group/user membership when using FSxN with nfs4"
+            # Valid idmapd configuration is required when using NetApp otherwise group membership will be set to `nobody`
+            # > https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/NFSv4.x_mounts_show_file_and_group_owner_as_nobody
+            cp /etc/idmapd.conf /etc/idmapd.conf.original.$(date +%s)
+            log_info "Check if Domain=${DS_DOMAIN_NAME} exists in idmapd.conf"
+            if grep -q "^[^#]*Domain=${DS_DOMAIN_NAME}" /etc/idmapd.conf; then
+              log_info "Domain=${DS_DOMAIN_NAME} already found in idmapd.conf, ignoring ..."
+            else
+              if grep -q '^[^#]*Domain=' /etc/idmapd.conf; then
+                log_info "Domain= found but not pointing to ${DS_DOMAIN_NAME}, remove the line ... "
+                sed -i '/^[^#]*Domain=/d' /etc/idmapd.conf
+              fi
+              log_info "Adding Domain=${DS_DOMAIN_NAME} under the [General] section on /etc/idmapd.conf"
+              sed -i "/^\[General\]/a Domain=${DS_DOMAIN_NAME}" /etc/idmapd.conf
+              nfsidmap -c
+            fi
+        fi
+        ENDPOINT="${NFS_DNS_NAME}:${FSX_VOLUME_JUNCTION_PATH}"
+      fi
+
+      if [[ "${SOCA_NODE_TYPE}" == "controller" ]]; then
+       # Check if tag soca:OntapFirstSetup == true is there, only applicable on the controller
+       # If yes, SOCA will proceed to initial CIFS/SVM configuration
+        local FSX_VOLUME_TAG_ONTAP_FIRST_SETUP=$(aws_cli fsx list-tags-for-resource --resource-arn "${FSX_VOLUME_RESOURCE_ARN}" --query "Tags[?Key=='soca:OntapFirstSetup'].Value" --output text)
+        if [[ "${FSX_VOLUME_TAG_ONTAP_FIRST_SETUP}" == "true" ]]; then
+          log_info "Tag soca:OntapFirstSetup = true exist on this FSx for NetApp ONTAP, processing to CIFS share creation and SVM conf"
+          {% include "templates/linux/shared_storage/fsx/ontap/first_setup.sh.j2" %}
+          fsx_ontap_first_setup "${MOUNT_TARGET}"
+        else
+          log_info "soca:OntapFirstSetup not present or not true, fsx_ontap_first_setup is not needed"
+        fi
+      fi
+
+      if fstab_wrapper "${ENDPOINT} ${MOUNT_PATH} nfs4 ${MOUNT_OPTIONS} 0 0"; then
+        log_info "Successfully mounted ${ENDPOINT} as ${MOUNT_PATH}"
+      else
+        if [[ ${ON_MOUNT_FAILURE} == "exit" ]]; then
+          exit_fail "Unable to mount ${ENDPOINT} as ${MOUNT_PATH}"
+        else
+          log_warning "Unable to mount ${ENDPOINT} as ${MOUNT_PATH}, ignoring"
+        fi
+      fi
+    else
+      log_warning "FSx ONTAP Filesystem ${MOUNT_TARGET}, mount path ${MOUNT_PATH} is not enabled. Skipping ... Detected enabled flag ${ENABLED}"
+    fi
+  }
 {% endif %}
 # End: FSx OnTap mount
