Push 25.3.0

diff --git a/installer/resources/user_data/login_node/01_user_data.sh.j2 b/installer/resources/user_data/login_node/01_user_data.sh.j2
--- a/installer/resources/user_data/login_node/01_user_data.sh.j2
+++ b/installer/resources/user_data/login_node/01_user_data.sh.j2
@@ -3,91 +3,85 @@
 # Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: Apache-2.0
 
-# Important: Keep this file < 16 KBs (AWS EC2 UserData requirement)
+# As UserData length is limited in size 16KB. Edit setup.sh.j2 instead.
 
 # Load common logging feature
 {% include "templates/linux/common/log.sh.j2" %}
 
-log_info "User Data Start Date: $(date)"
-
-# Load packages management functions
-{% include "templates/linux/system_packages/packages_management.sh.j2" %}
-
-# Load common File Download wrapper
-{% include "templates/linux/common/file_download.sh.j2" %}
+# Patch DNS Resolver when using Debian based distributions
+{% include "templates/linux/dns_resolver.sh.j2" %}
 
 # Configure HTTP proxy if any
 {% include "templates/linux/http_proxy.sh.j2" %}
 
-source /etc/environment
-
-{% if context.get("/configuration/BaseOS") == "centos7" %}
-  # CentOS7 is EOL, manual patch to support Yum repo
-  {% include "templates/linux/patch_centos7_repos.sh.j2" %}
-{% endif %}
-
-# Install awscli
-{% include "templates/linux/awscli.sh.j2" %}
-
-# Load custom wrappers
+# Load Custom Wrappers
+{% include "templates/linux/common/file_download.sh.j2" %}
 {% include "templates/linux/common/wrapper_awscli.sh.j2" %}
 {% include "templates/linux/common/wrapper_imds.sh.j2" %}
-{% include "templates/linux/common/setup_environment_file.sh.j2" %}
+
+# Load packages management functions
+{% include "templates/linux/system_packages/packages_management.sh.j2" %}
 
 # Install AWS Systems Manager agent
 {% include "templates/linux/aws_ssm_agent.sh.j2" %}
 
-# Note: Log generated prior to filesystems mount will be automatically copied over the POST_FILESYSTEM_MOUNT_LOGS_FOLDER post filesystems mount
-PRE_FILESYSTEM_MOUNT_LOGS_FOLDER="/root/soca_boostrap_$(instance_id)/logs"
-POST_FILESYSTEM_MOUNT_LOGS_FOLDER="{{ context.get("/job/BootstrapPath") }}/$(hostname -s)/$(date +%s)"
+# Install awscli
+{% include "templates/linux/awscli.sh.j2" %}
 
 # Remove any previous references of SOCA to the environment file (if any)
 cp /etc/environment /etc/environment.original.$(date +%s)
-sed -i '/[SOCA_DO_NOT_DELETE]/d' /etc/environment
+sed -i '/SOCA_/d' /etc/environment
 
-# Set Environment Variables
-set_environment_variable "AWS_DEFAULT_REGION" "{{ context.get("/configuration/Region") }}"
-set_environment_variable "SOCA_BOOTSTRAP_ASSETS_FOLDER" "/root/soca_boostrap_$(instance_id)"
-set_environment_variable "SOCA_BOOTSTRAP_LOGS_FOLDER" ${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}
-set_environment_variable "SOCA_CLUSTER_ID" "{{ context.get("/configuration/ClusterId") }}"
+# Note: Log generated prior to filesystems mount will be automatically copied over the POST_FILESYSTEM_MOUNT_LOGS_FOLDER post filesystems mount for simple troubleshooting
+PRE_FILESYSTEM_MOUNT_LOGS_FOLDER="/root/soca_bootstrap_$(instance_id)/logs"
+POST_FILESYSTEM_MOUNT_LOGS_FOLDER="{{ context.get("/job/BootstrapPath") }}/$(hostname -s)"
+SOCA_BOOTSTRAP_ASSETS_FOLDER="/root/soca_bootstrap_$(instance_id)"
 
-# Create SOCA Bootstrap structure
-mkdir -p ${SOCA_BOOTSTRAP_ASSETS_FOLDER}
 mkdir -p ${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}
 
-# Mount Filesystems
-{% include "templates/linux/filesystems_automount.sh.j2" %}
+log_info "EC2 UserData script is being executed, checks logs on /var/log/cloud-init*" >> "${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}/01_user_data.sh.log" 2>&1
 
-# Wait until SOCA is ready
-VERIFY_FILE_COUNT=0
-while [[ ! -d "/apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_node_bootstrap/" ]]; do
-     log_info "/apps/soca/{{ context.get("/configuration/ClusterId") }} not ready yet"
-     if [[ ${VERIFY_FILE_COUNT} -gt 30 ]]; then
-      exit_fail "Unable to verify filesystem"
-     fi
-    ((VERIFY_FILE_COUNT++))
-    sleep 60
+# Retrieve Boostrap sequence from S3
+{% if context.get("/configuration/Region") in ('us-gov-east-1', 'us-gov-west-1')  %}
+  S3_BUCKET_REGION=$(curl -s --head {{ context.get("/configuration/S3Bucket") }}.s3.{{ context.get("/configuration/Region") }}.amazonaws.com | grep bucket-region | awk '{print $2}' | tr -d '\r\n')
+{% else %}
+  S3_BUCKET_REGION=$(curl -s --head {{ context.get("/configuration/S3Bucket") }}.s3.amazonaws.com | grep bucket-region | awk '{print $2}' | tr -d '\r\n')
+{% endif %}
+
+log_info "Downloading SOCA_BOOTSTRAP_SEQUENCE:  {{ context.get("/job/BootstrapScriptsS3Location") }}"
+aws_cli s3 --region ${S3_BUCKET_REGION} sync {{ context.get("/job/BootstrapScriptsS3Location") }} ${SOCA_BOOTSTRAP_ASSETS_FOLDER}
+
+# Install Required System library/packages
+/bin/bash "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/install_required_packages.sh" >> "${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}/install_required_packages.sh.log" 2>&1
+
+# Mount Filesystems
+/bin/bash "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/filesystems_automount.sh" >> "${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}/filesystems_mount.log" 2>&1
+
+# Create new log path in shared partition
+mkdir -p ${POST_FILESYSTEM_MOUNT_LOGS_FOLDER}
+
+# Copy the User Data log into the shared filesystem to simplify troubleshooting
+cp /var/log/messages ${POST_FILESYSTEM_MOUNT_LOGS_FOLDER} || echo "/var/log/messages found on this system"
+cp /var/log/cloud-init* ${POST_FILESYSTEM_MOUNT_LOGS_FOLDER} || echo "/var/log/cloud-init not found on this system"
+cp -r ${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}/* ${POST_FILESYSTEM_MOUNT_LOGS_FOLDER}
+
+
+# Final setup script is created and uploaded by the Controller Host
+# Since Login Node(s) is provisioned at SOCA install time, not all parameters are known.
+# The controller will wait for CDK to be complete, then generate the final setup.sh script for the login node and finally upload it to S3
+MAX_ATTEMPTS_FETCH_SETUP=10
+ATTEMPT_FETCH_SETUP=0
+while ! aws s3 ls "{{ context.get("/job/BootstrapScriptsS3Location") }}/02_setup.sh" >/dev/null 2>&1; do
+    if [[ ${ATTEMPT_FETCH_SETUP} -ge ${MAX_ATTEMPTS_FETCH_SETUP} ]]; then
+        exit_fail "Unable to fetch {{ context.get("/job/BootstrapScriptsS3Location") }}/02_setup.sh after 10 attempts."
+    fi
+    log_warning "{{ context.get("/job/BootstrapScriptsS3Location") }}/02_setup.sh does not exist yet, waiting for SOCA Controller to create it (Attempt: $((ATTEMPT_FETCH_SETUP+1)))"
+    ATTEMPT_FETCH_SETUP=$((ATTEMPT_FETCH_SETUP + 1))
+    sleep 120
 done
 
-# Post Filesystems Mount, override SOCA_BOOTSTRAP_LOGS_FOLDER to point to the shared filesystem
-set_environment_variable "SOCA_BOOTSTRAP_LOGS_FOLDER" ${POST_FILESYSTEM_MOUNT_LOGS_FOLDER}
-mkdir -p ${SOCA_BOOTSTRAP_LOGS_FOLDER}
+# Setup Script is ready, downloading it
+aws_cli s3 --region ${S3_BUCKET_REGION} cp "{{ context.get("/job/BootstrapScriptsS3Location") }}/02_setup.sh" ${SOCA_BOOTSTRAP_ASSETS_FOLDER}
 
-log_info "Boostrap Asset Folder: ${SOCA_BOOTSTRAP_ASSETS_FOLDER}"
-log_info "Boostrap Logs Folder: ${SOCA_BOOTSTRAP_LOGS_FOLDER}"
-
-# Copy the User Data logs into the shared filesystem to simplify troubleshooting
-cp /var/log/messages ${SOCA_BOOTSTRAP_LOGS_FOLDER} || echo "/var/log/messages found on this system"
-cp /var/log/cloud-init* ${SOCA_BOOTSTRAP_LOGS_FOLDER} || echo "/var/log/cloud-init not found on this system"
-cp "${PRE_FILESYSTEM_MOUNT_LOGS_FOLDER}/*" ${SOCA_BOOTSTRAP_LOGS_FOLDER}
-
-# Generate bootstrap script and execute it
-/bin/bash /apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_manager/tools/j2generator/j2generator.sh --get-template "compute_node/02_setup.sh.j2" \
-    --output-file "{{ context.get("/job/BootstrapPath") }}/02_setup.sh" \
-    --ssm-key "/" \
-    --add-value "KEY=/job/NodeType VALUE=login_node TYPE=str" \
-    --template-dirs "/apps/soca/{{ context.get("/configuration/ClusterId") }}/cluster_node_bootstrap/"
-
-log_info "User Data End: $(date)"
-
-/bin/bash {{ context.get("/job/BootstrapPath") }}/02_setup.sh >> ${SOCA_BOOTSTRAP_LOGS_FOLDER}/02_setup.sh.log 2>&1
+# Execute final setup
+/bin/bash "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/02_setup.sh" >> "${POST_FILESYSTEM_MOUNT_LOGS_FOLDER}/02_setup.log" 2>&1
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/filesystems_automount.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/filesystems_automount.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/filesystems_automount.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/filesystems_automount.sh.j2
@@ -1,30 +1,101 @@
 # Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: Apache-2.0
 
-# Download SOCA FileSystems AutoMount from S3 and execute it
 # This script will mount all filesystems specified on SSM in /configuration/FileSystems tree
-# Note: soca_filesystems_automount.sh is generated at install time, template code is available under installer/resources/script
-# File is then uploaded to S3 during the first install
 
-if [[ -z "${S3_BUCKET_REGION}" ]]; then
-  {% if context.get("/configuration/Region") in ('us-gov-east-1', 'us-gov-west-1')  %}
-    S3_BUCKET_REGION=$(curl -s --head {{ context.get("/configuration/S3Bucket") }}.s3.{{ context.get("/configuration/Region") }}.amazonaws.com | grep bucket-region | awk '{print $2}' | tr -d '\r\n')
-  {% else %}
-    S3_BUCKET_REGION=$(curl -s --head {{ context.get("/configuration/S3Bucket") }}.s3.amazonaws.com | grep bucket-region | awk '{print $2}' | tr -d '\r\n')
-  {% endif %}
+# Do not include this template from another template in your bootstrap sequence. Instead render and save it as a file.
+
+{% include "templates/linux/common.sh.j2" %}
+
+{% include "templates/linux/shared_storage/mount_efs.sh.j2" %}
+
+{% include "templates/linux/shared_storage/mount_fsx_lustre.sh.j2" %}
+
+{% include "templates/linux/shared_storage/mount_fsx_ontap.sh.j2" %}
+
+{% include "templates/linux/shared_storage/mount_fsx_openzfs.sh.j2" %}
+
+{% include "templates/linux/shared_storage/mount_standalone_nfs.sh.j2" %}
+
+{% include "templates/linux/shared_storage/mount_s3.sh.j2" %}
+
+# Retrieve SocaConfig "/configuration/Filesystems" which contains all the FileSystem mount logic, return a dictionary of key/v
+SOCA_FILESYSTEMS_SSM_TREE=$(aws_cli ssm get-parameters-by-path --path "/soca/{{ context.get("/configuration/ClusterId") }}/configuration/FileSystems"  \
+  --recursive \
+  --with-decryption \
+  --query "Parameters" \
+  --output json)
+
+log_info "Retrieved SOCA FileSystem Tree: ${SOCA_FILESYSTEMS_SSM_TREE}"
+
+# Install jq if not already there
+if ! verify_package_installed jq; then
+  log_info "jq not found, installing it ..."
+  packages_install jq
 fi
 
-mkdir -p ${SOCA_BOOTSTRAP_ASSETS_FOLDER}/soca_filesystems_automount
-pushd ${SOCA_BOOTSTRAP_ASSETS_FOLDER}
+# Transform SSM Hierarchy into readable dictionary
+FS_MAP=$(echo "$SOCA_FILESYSTEMS_SSM_TREE" | jq -r --arg prefix "/soca/{{ context.get("/configuration/ClusterId") }}/configuration/FileSystems/" '
+  reduce map({key: .Name | sub($prefix; ""), value: .Value})[] as $item ({};
+    ($item.key | split("/")) as $keys |
+    setpath($keys; $item.value)
+  )
+')
 
-log_info "Downloading SocaFileSystemsAutomount scripts from s3"
-aws_cli s3 --region ${S3_BUCKET_REGION}  cp s3://{{ context.get("/configuration/S3Bucket") }}/{{ context.get("/configuration/ClusterId") }}/config/do_not_delete/scripts/soca_filesystems_automount.sh .
+echo "${FS_MAP}" | jq -r 'keys[]' | while read FS_NAME; do
+  # Filesystem Provider (fsx_ontap, fsx_lustre, efs ...)
+  PROVIDER=$(echo "${FS_MAP}" | jq -r ".${FS_NAME}.provider")
 
-log_info "Executing SocaFileSystemsAutoMount mount"
-if /bin/bash soca_filesystems_automount.sh >> ${SOCA_BOOTSTRAP_LOGS_FOLDER}/soca_filesystems_automount.sh.log 2>&1; then
-  log_info "SocaFileSystemsAutoMount completed successfully"
-else
-  log_error "SocaFileSystemsAutoMount failed. Check logs."
-fi
+  # Whether or not the FSx is enabled or not
+  ENABLED=$(echo "${FS_MAP}" | jq -r ".${FS_NAME}.enabled // \"true\"")
 
-popd
+  # Unix path where to mount this filesystem
+  MOUNT_PATH=$(echo "${FS_MAP}" | jq -r ".${FS_NAME}.mount_path")
+
+  # Endpoint to be mounted (volume ID, filesystem ID ...)
+  MOUNT_TARGET=$(echo "${FS_MAP}" | jq -r ".${FS_NAME}.mount_target")
+
+  # Option for the mount
+  MOUNT_OPTIONS=$(echo "$FS_MAP" | jq -r ".${FS_NAME}.mount_options")
+
+  # What to do if the mount is not successful (either ignore or exit)
+  ON_MOUNT_FAILURE=$(echo "${FS_MAP}" | jq -r ".${FS_NAME}.on_mount_failure //  \"ignore\"")
+
+  log_info "Processing ${PROVIDER}: $(echo "${FS_MAP}" | jq -r ".${FS_NAME}")"
+
+  case "${PROVIDER}" in
+  "efs")
+    MOUNT_FUNCTION="mount_efs"
+    ;;
+  "nfs")
+    MOUNT_FUNCTION="mount_nfs"
+    ;;
+  "fsx_lustre")
+    MOUNT_FUNCTION="mount_fsx_lustre"
+    ;;
+  "fsx_ontap")
+    MOUNT_FUNCTION="mount_fsx_ontap"
+    ;;
+  "fsx_openzfs")
+    MOUNT_FUNCTION="mount_openzfs"
+    ;;
+  "s3")
+    MOUNT_FUNCTION="mount_s3"
+    ;;
+  *)
+    exit_fail "Unrecognized Storage Provider ${PROVIDER} for ${FS_NAME} , must be efs / nfs / fsx_lustre / fsx_ontap / fsx_openzfs or s3"
+    ;;
+  esac
+
+  if ! eval ${MOUNT_FUNCTION} --mount-path="${MOUNT_PATH}" \
+        --mount-target="${MOUNT_TARGET}" \
+        --mount-options="${MOUNT_OPTIONS}" \
+        --on-mount-failure="${ON_MOUNT_FAILURE}" \
+        --enabled="${ENABLED}"; then
+
+      exit_fail "Error while trying to mount ${MOUNT_TARGET} via ${MOUNT_FUNCTION}, check log"
+  fi
+
+done
+
+log_info "SocaFileSystemsAutoMount Completed"
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2
@@ -5,14 +5,16 @@ function build_openpbs {
   pushd ${1}
   log_info "Building OpenPBS from $(pwd)"
   local NCPUS=$(nproc)
+  local SOCA_PYTHON="/opt/soca/{{ context.get('/configuration/ClusterId') }}/python"
   log_info "Running AutoGen"
 
   if ! ./autogen.sh; then
     exit_fail "Unable to run autogen.sh for OpenPBS. See log for additional details"
   fi
-  log_info "Running Configure"
+  log_info "Running Configure, adding SOCA Python location to rpath"
 
-  if ! ./configure --prefix=/opt/pbs; then
+  # objdump -x /opt/pbs/sbin/pbs_sched | grep RPATH ensure this contains path to SOCA_PYTHON for hooks
+  if ! LDFLAGS="-Wl,-rpath,${SOCA_PYTHON}/latest/lib" ./configure --prefix=/opt/pbs --with-python=${SOCA_PYTHON}/latest; then
     exit_fail "Unable to run ./configure --prefix=/opt/pbs for OpenPBS. See log for additional details"
   fi
 
@@ -60,40 +62,55 @@ function openpbs_install {
 
     {% elif context.get("/configuration/SchedulerDeploymentType") == "git" %}
       log_info "Installing OpenPBS via git"
-      local OPENBS_GIT_REPO="{{ context.get("/system/scheduler/openpbs/git/repo") }}"
-      local OPENBS_GIT_BRANCH="{{ context.get("/system/scheduler/openpbs/git/branch") }}"
-      local OPENBS_GIT_COMMIT_ID="{{ context.get("/system/scheduler/openpbs/git/commit_id") }}"
+      local OPENPBS_GIT_REPO="{{ context.get("/system/scheduler/openpbs/git/repo") }}"
+      local OPENPBS_GIT_BRANCH="{{ context.get("/system/scheduler/openpbs/git/branch") }}"
+      local OPENPBS_GIT_COMMIT_ID="{{ context.get("/system/scheduler/openpbs/git/commit_id") }}"
       local OPENPBS_VERSION="{{ context.get("/system/scheduler/openpbs/tgz/version") }}"
 
       if [[ "${OPENPBS_INSTALLED_VERS}" != "${OPENPBS_VERSION}" ]]; then
           log_info "OpenPBS Not Detected, Installing OpenPBS"
           # Note: clone in current directory without checkout to avoid new folder creation
-          git clone ${OPENBS_GIT_REPO} --no-checkout {% if context.get("/system/scheduler/openpbs/git/branch") %}--branch ${OPENBS_GIT_BRANCH} {% endif %} ${INSTALLER_DIR}
+          git clone ${OPENPBS_GIT_REPO} --no-checkout {% if context.get("/system/scheduler/openpbs/git/branch") %}--branch ${OPENPBS_GIT_BRANCH} {% endif %} ${INSTALLER_DIR}
 
           # Load actual content
           {% if context.get("/system/scheduler/openpbs/git/commit_id") %}
-          git checkout ${OPENBS_GIT_COMMIT_ID}
+            git checkout ${OPENPBS_GIT_COMMIT_ID}
           {% else %}
-          git checkout
+            git checkout
           {% endif %}
 
           # Install Pre-requisite
-          if ! verify_package_installed cmake3; then
-            log_info "cmake3 not installed, installing it "
-            packages_install cmake3
+          {% if context.get("/configuration/BaseOS") in ("ubuntu2204", "ubuntu2404") %}
+            # Debian Based Distro
+            if ! verify_package_installed cmake; then
+              log_info "cmake version 3+ not installed, installing it"
+              packages_install cmake
+            fi
+          {% else %}
+            # RedHat based Distro
+            if ! verify_package_installed cmake3; then
+              log_info "cmake version 3+ not installed, installing it"
+              packages_install cmake3
+            fi
+          {% endif %}
+
+
+          # todo: understand why libcjson(-dev) from yum does not work here
+          if test ! -e "/lib64/libcjson.so"; then
+              log_info "/lib64/libcjson.so not found, installing it"
+              git clone https://github.com/DaveGamble/cJSON.git
+              pushd cJSON
+              mkdir build
+              pushd build
+              {% if context.get("/configuration/BaseOS") in ("ubuntu2204", "ubuntu2404") %}
+                cmake ..
+              {% else %}
+                cmake3 ..
+              {% endif %}
+              make
+              make install
+              ln -sf /usr/local/lib64/libcjson.so.1 /lib64/libcjson.so.1
           fi
-         # todo: understand why libcjson(-dev) from yum does not work here
-         if test ! -e "/lib64/libcjson.so"; then
-          log_info "/lib64/libcjson.so not found, installing it"
-          git clone https://github.com/DaveGamble/cJSON.git
-          pushd cJSON
-          mkdir build
-          pushd build
-          cmake3 ..
-          make
-          make install
-          ln -sf /usr/local/lib64/libcjson.so.1 /lib64/libcjson.so.1
-        fi
 
         build_openpbs ${INSTALLER_DIR}
 
@@ -119,7 +136,6 @@ function openpbs_install {
       exit_fail "{{ context.get("/configuration/scheduler/deployment_type") }} must be tgz or git"
 
     {% endif %}
-
     popd
     log_info "Completed OpenPBS installation"
 }
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2
@@ -1,11 +1,6 @@
 # Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: Apache-2.0
 
-# Begin: Install Python on the Controller Host
-# This function install SOCA python. It's only executing by the Controller Host during the first boot.
-# SOCA python is the backbone of SOCA, responsible to run all scripts under cluster_manager, cluster_analytics, cluster_web_ui etc ...
-# It's not recommended to change this template
-{% if context.get("/configuration/BaseOS") in ("amazonlinux2", "amazonlinux2023", "centos7", "rhel7", "rhel8", "rhel9", "rocky8", "rocky9") %}
 function install_soca_python () {
   log_info "Installing SOCA Python"
   mkdir -p "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/soca_python"
@@ -13,22 +8,46 @@ function install_soca_python () {
   local PYTHON_VERSION="{{ context.get("/system/python/version") }}"
   local PYTHON_URL="{{ context.get("/system/python/url") }}"
   local PYTHON_SHA256="{{ context.get("/system/python/sha256") }}"
-  local PYTHON_INSTALLED_VERS=$(/apps/soca/"{{ context.get("/configuration/ClusterId") }}"/python/latest/bin/python3 --version | awk {'print $NF'})
+  local SOCA_PYTHON_LOCAL_INSTALL_PREFIX="/opt/soca/{{ context.get("/configuration/ClusterId") }}/python/${PYTHON_VERSION}/$(uname -m)/{{ context.get('/configuration/BaseOS') }}"
+  local SOCA_PYTHON_VENV="${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/soca-python-virtual-env"
+  local SOCA_PYTHON_SITE_PACKAGES
 
-  if [[ "${PYTHON_INSTALLED_VERS}" != "${PYTHON_VERSION}" ]]; then
-    log_info "SOCA Python not detected, installing"
+  if [[ $(${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/bin/python3 --version | awk {'print $NF'}) == "${PYTHON_VERSION}" ]]; then
+    log_info "Local SOCA_PYTHON ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} found and at correct version, skipping SOCA_PYTHON Install"
+
+  else
+    log_info "Local SOCA_PYTHON ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} not found, installing it"
+    mkdir -p ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}
+    log_info "${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/bin/python3 not detected or at wrong version, installing Python ${PYTHON_VERSION}"
     mkdir -p "{{ context.get("/configuration/ClusterId") }}"/python/installer
     pushd "{{ context.get("/configuration/ClusterId") }}"/python/installer
     file_download --download-url="${PYTHON_URL}" --save-as="python3_soca_installer.tgz" --sha256-checksum="${PYTHON_SHA256}"
     tar xvf "python3_soca_installer.tgz" --strip-components=1 -C .
-    if ! ./configure CXX="g++" \
-      LDFLAGS="-L/usr/lib64/openssl" \
-      CPPFLAGS="-I/usr/include/openssl" \
-      -enable-loadable-sqlite-extensions \
-      --prefix="/apps/soca/{{ context.get("/configuration/ClusterId") }}/python/${PYTHON_VERSION}" \
-      --enable-optimizations; then
+
+    {% if context.get("/job/NodeType") == "controller" %}
+      # Add additional compilation flags for Controller as Python will be used for web interface & other tasks
+      if ! ./configure CXX="g++" \
+        LDFLAGS="-L/usr/lib64/openssl" \
+        CPPFLAGS="-I/usr/include/openssl" \
+        CLAGS="fPIC" \
+        --enable-loadable-sqlite-extensions \
+        --prefix=${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} \
+        --enable-optimizations \
+        --enable-shared \
+        --with-ensurepip=install; then
         exit_fail "Unable to run './configure' for SOCA_PYTHON. Check bootstrap logs."
-    fi
+      fi
+    {% else %}
+      # Minimal Python3 environment to build OpenPBS
+      if ! ./configure CXX="g++" \
+        LDFLAGS="-L/usr/lib64/openssl" \
+        CPPFLAGS="-I/usr/include/openssl" \
+        CLAGS="fPIC" \
+        --prefix=${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} \
+        --enable-shared; then
+        exit_fail "Unable to run './configure' for SOCA_PYTHON. Check bootstrap logs."
+      fi
+    {% endif %}
 
     if ! make -j$(nproc); then
       exit_fail "Unable to run 'make' for SOCA_PYTHON. Check bootstrap logs."
@@ -38,23 +57,44 @@ function install_soca_python () {
        exit_fail "Unable to run 'make install' for SOCA_PYTHON. Check bootstrap logs."
     fi
 
+    log_info "Creating symlink /opt/soca/{{ context.get("/configuration/ClusterId") }}/python/latest pointing to ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}"
+    ln -sf ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} "/opt/soca/{{ context.get("/configuration/ClusterId") }}/python/latest"
     popd
-    popd
-    ln -sf "/apps/soca/{{ context.get("/configuration/ClusterId") }}/python/${PYTHON_VERSION}" "/apps/soca/{{ context.get("/configuration/ClusterId") }}/python/latest"
-  else
-    log_info "Python already installed and at correct version (${PYTHON_VERSION})."
+
+    log_info "SOCA_PYTHON installed successfully, updating dynamic linker cache"
+    # ensure 99- is there to avoid version conflict if /lib64 system python3 is already at the same version
+    echo "/lib64" > /etc/ld.so.conf.d/00-system-python.conf # ensure system python is always loaded first
+    echo "/opt/soca/{{ context.get('/configuration/ClusterId') }}/python/latest/lib" > /etc/ld.so.conf.d/99-python-{{ context.get('/configuration/ClusterId') }}.conf
+    if ! ldconfig; then
+      exit_fail "SOCA_PYTHON installed but unable to update ldconfig. Check bootstrap logs"
+    fi
+
+    # Install Python required libraries
+    {% if context.get("/job/NodeType") == "controller" %}
+      echo "{%- include "templates/linux/soca_python_controller_requirements.txt.j2" -%}" > requirements.txt
+    {% else %}
+      echo "{%- include "templates/linux/soca_python_compute_node_requirements.txt.j2" -%}" > requirements.txt
+    {% endif %}
+
+    log_info "Creating ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/soca_python.env"
+    echo "
+export PYTHONPATH=/opt/soca/{{ context.get("/configuration/ClusterId") }}/cluster_manager/
+export PYTHONUSERBASE=${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}
+export PYTHONEXECUTABLE=${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/bin/python3
+" > ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/soca_python.env
+
+    # Source SOCA_PYTHON Environment.
+    # This command is also applied to all other scripts via common.sh.j2
+    source ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/soca_python.env
+
+    # --user to make sure python libs are installed in the SOCA_PYTHON path only (we don't touch system python)
+    if ! ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/bin/pip3 install --user -r requirements.txt; then
+        exit_fail "Unable to install SOCA Python requirements (see templates/linux/soca_python_requirements.txt.j2)"
+    fi
+
   fi
-
-  # Install Python required libraries
-  echo "{%- include "templates/linux/soca_python_requirements.txt.j2" -%}" > requirements.txt
-
-  if ! /apps/soca/{{ context.get("/configuration/ClusterId") }}/python/${PYTHON_VERSION}/bin/pip3 install -r requirements.txt; then
-    exit_fail "Unable to install SOCA Python requirements (see templates/linux/soca_python_requirements.txt.j2)"
-  fi
-
   popd
   log_info "Python and relevant dependency installed"
 }
 install_soca_python
-{% endif %}
 # End: : Install Python on the Controller Host
