Push 25.5.0

diff --git a/source/soca/cluster_node_bootstrap/templates/linux/gpu/nvidia_drivers.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/gpu/nvidia_drivers.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/gpu/nvidia_drivers.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/gpu/nvidia_drivers.sh.j2
@@ -3,6 +3,9 @@
 
 # Begin: Install GPU Drivers - Is GPU Instance Type
 function install_nvidia_grid_drivers () {
+  local GRID_VERSION="${1}"
+  log_info "Installing Grid Nvidia ${GRID_VERSION}"
+
   which nvidia-smi > /dev/null 2>&1
   if [[ "$?" == "0" ]]; then
     log_info "GPU driver already installed. Skip."
@@ -17,17 +20,21 @@ function install_nvidia_grid_drivers () {
   pushd "${SOCA_BOOTSTRAP_ASSETS_FOLDER}/gpu_drivers"
   rm -rf NVIDIA-Linux-x86_64*.run || log_info "No previous .run file detected"
   local DRIVER_BUCKET_REGION=$(curl -s --head "{{ context.get("/system/gpu/gpu_settings/nvidia/linux/grid_drivers/s3_bucket_url") }}" | grep bucket-region | awk '{print $2}' | tr -d '\r\n')
-  aws_cli --region ${DRIVER_BUCKET_REGION} s3 cp --quiet --recursive "{{ context.get("/system/gpu/gpu_settings/nvidia/linux/grid_drivers/s3_bucket_path") }}" .
+  aws_cli --region ${DRIVER_BUCKET_REGION} s3 cp --quiet --recursive "{{ context.get("/system/gpu/gpu_settings/nvidia/linux/grid_drivers/s3_bucket_path") }}/${GRID_VERSION}/" .
   local x_server_pid=$(cat /tmp/.X0-lock)
   if [[ ! -z "${x_server_pid}" ]]; then
     kill $x_server_pid
   fi
-  log_info "Installing NVIDIA Drivers with  NVIDIA-Linux-x86_64*.run --no-precompiled-interface --run-nvidia-xconfig --no-questions --accept-license --silent --no-unified-memory"
-  /bin/bash NVIDIA-Linux-x86_64*.run --no-precompiled-interface \
-   --run-nvidia-xconfig \
-   --no-questions \
-   --accept-license \
-   --silent
+  log_info "Installing NVIDIA Drivers with NVIDIA-Linux-x86_64*.run --no-precompiled-interface --run-nvidia-xconfig --no-questions --accept-license --silent --no-unified-memory"
+  if ! /bin/bash NVIDIA-Linux-x86_64*.run --no-precompiled-interface \
+    --run-nvidia-xconfig \
+    --no-questions \
+    --accept-license \
+    --silent;
+  then
+    log_error "Unable to install GPU driver, check /var/log/nvidia-installer.log for more info. Trying to install a compatibility driver ..."
+  fi
+
   log_info "X server configuration for GPU start..."
   rm -rf /etc/X11/XF86Config*
   local NVIDIA_XCONFIG=$(which nvidia-xconfig)
@@ -41,7 +48,7 @@ function install_nvidia_grid_drivers () {
 function install_nvidia_public_tesla_drivers() {
   local DRIVER_VERSION="${1}"
   local MACHINE=$(uname -m)
-  local DRIVER_URL_ENDPOINT="{{ context.get("/system/gpu/gpu_settings/nvidia/linux/tesla_drivers/public_driver_url_endpoint") }}"
+  local DRIVER_URL_ENDPOINT="{{ context.get("/system/gpu/gpu_settings/nvidia/linux/tesla_drivers/public_driver_url_endpoint") }}/${DRIVER_VERSION}/NVIDIA-Linux-${MACHINE}-${DRIVER_VERSION}.run"
 
   which nvidia-smi > /dev/null 2>&1
   if [[ "$?" == "0" ]]; then
@@ -65,11 +72,13 @@ function install_nvidia_public_tesla_drivers() {
 
   log_info "Installing NVIDIA Drivers with  NVIDIA-Linux-x86_64*.run --no-precompiled-interface --run-nvidia-xconfig --no-questions --accept-license --silent --no-unified-memory"
 
-  /bin/bash NVIDIA-Linux-x86_64*.run --no-precompiled-interface \
+  if ! /bin/bash NVIDIA-Linux-x86_64*.run --no-precompiled-interface \
    --run-nvidia-xconfig \
    --no-questions \
    --accept-license \
-   --silent
+   --silent; then
+   log_error "Unable to install GPU driver, check /var/log/nvidia-installer.log for more info. Trying to install a compatibility driver ..."
+  fi
 
   log_info "X server configuration for GPU start..."
   rm -rf /etc/X11/XF86Config*
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/scheduler/openpbs/install.sh.j2
@@ -6,13 +6,58 @@ function build_openpbs {
   log_info "Building OpenPBS from $(pwd)"
   local NCPUS=$(nproc)
   local SOCA_PYTHON="/opt/soca/{{ context.get('/configuration/ClusterId') }}/python"
-  log_info "Running AutoGen"
+  {% if context.get("/configuration/BaseOS") in ("amazonlinux2", "rhel8", "rocky8") %}
+    log_info "Detected old Linux Distro, patching libtool/automake/pkg-config to make sure we can compile OpenPBS with python3.13"
+    local COMPAT_PACKAGE_INSTALLER_PATH="/opt/soca/{{ context.get('/configuration/ClusterId') }}/packages"
 
+    log_info "Installing custom automake ${COMPAT_PACKAGE_INSTALLER_PATH}/automake"
+    file_download --download-url="{{ context.get("/system/scheduler/openpbs/compatibility_packages/automake/url") }}" --save-as="automake_installer.tar.gz" --sha256-checksum="{{ context.get("/system/scheduler/openpbs/compatibility_packages/automake/sha256") }}"
+    mkdir automake_installer
+    tar zxvf automake_installer.tar.gz --strip-components=1 -C automake_installer
+    pushd automake_installer
+    ./configure --prefix="${COMPAT_PACKAGE_INSTALLER_PATH}/automake"
+    make -j${NCPUS}
+    make install -j${NCPUS}
+    popd
+
+    log_info "Installing custom libtool ${COMPAT_PACKAGE_INSTALLER_PATH}/libtool"
+    file_download --download-url="{{ context.get("/system/scheduler/openpbs/compatibility_packages/libtool/url") }}" --save-as="libtool_installer.tar.gz" --sha256-checksum="{{ context.get("/system/scheduler/openpbs/compatibility_packages/libtool/sha256") }}"
+    mkdir libtool_installer
+    tar zxvf libtool_installer.tar.gz --strip-components=1 -C libtool_installer
+    pushd libtool_installer
+    ./configure --prefix="${COMPAT_PACKAGE_INSTALLER_PATH}/libtool"
+    make -j${NCPUS}
+    make install -j${NCPUS}
+    popd
+
+    log_info "Installing custom pkg-config ${COMPAT_PACKAGE_INSTALLER_PATH}/pkg-config"
+    file_download --download-url="{{ context.get("/system/scheduler/openpbs/compatibility_packages/pkgconfig/url") }}" --save-as="pkg-config_installer.tar.gz" --sha256-checksum="{{ context.get("/system/scheduler/openpbs/compatibility_packages/pkgconfig/sha256") }}"
+    mkdir pkg-config_installer
+    tar -xvzf pkg-config_installer.tar.gz --strip-components=1 -C pkg-config_installer
+    pushd pkg-config_installer
+    ./configure --with-internal-glib --prefix="${COMPAT_PACKAGE_INSTALLER_PATH}/pkgconfig"
+    make
+    make install
+
+    log_info "Exporting custom path for all compat-packages"
+    export PKG_CONFIG_PATH="${COMPAT_PACKAGE_INSTALLER_PATH}/pkgconfig/bin/pkg-config"
+    export LIBTOOL="${COMPAT_PACKAGE_INSTALLER_PATH}/libtool/bin/libtool"
+    export AUTOMAKE="${COMPAT_PACKAGE_INSTALLER_PATH}/automake/bin/automake"
+    export ACLOCAL="${COMPAT_PACKAGE_INSTALLER_PATH}/automake/bin/aclocal"
+    export ACLOCAL_PATH="${COMPAT_PACKAGE_INSTALLER_PATH}/libtool/share/aclocal:${COMPAT_PACKAGE_INSTALLER_PATH}/automake/share/aclocal:${COMPAT_PACKAGE_INSTALLER_PATH}/pkgconfig/share/aclocal"
+
+    log_info "Running autoreconf"
+    autoreconf -fi
+    popd
+
+  {% endif %}
+
+  log_info "Running AutoGen"
   if ! ./autogen.sh; then
     exit_fail "Unable to run autogen.sh for OpenPBS. See log for additional details"
   fi
-  log_info "Running Configure, adding SOCA Python location to rpath"
 
+  log_info "Running Configure, adding SOCA Python location to rpath"
   # objdump -x /opt/pbs/sbin/pbs_sched | grep RPATH ensure this contains path to SOCA_PYTHON for hooks
   if ! LDFLAGS="-Wl,-rpath,${SOCA_PYTHON}/latest/lib" ./configure --prefix=/opt/pbs --with-python=${SOCA_PYTHON}/latest; then
     exit_fail "Unable to run ./configure --prefix=/opt/pbs for OpenPBS. See log for additional details"
@@ -20,12 +65,12 @@ function build_openpbs {
 
   log_info "Running Make"
 
-  if ! make -j ${NCPU}; then
+  if ! make -j${NCPU}; then
     exit_fail "Unable to run make -j ${NCPU} for OpenPBS. See log for additional details"
   fi
 
-  if ! make install -j ${NCPU}; then
-    exit_fail "Unable to run make install -j ${NCPU} for OpenPBS. See log for additional details"
+  if ! make install -j${NCPU}; then
+    exit_fail "Unable to run make install -j${NCPU} for OpenPBS. See log for additional details"
   fi
 
   log_info "Post Build Command"
@@ -96,9 +141,9 @@ function openpbs_install {
 
 
           # todo: understand why libcjson(-dev) from yum does not work here
-          if test ! -e "/lib64/libcjson.so"; then
-              log_info "/lib64/libcjson.so not found, installing it"
-              git clone https://github.com/DaveGamble/cJSON.git
+          if test ! -e "/lib64/libcjson.so.1"; then
+              log_info "/lib64/libcjson.so.1 not found, installing it"
+              git clone {{ context.get("/system/scheduler/openpbs/compatibility_packages/cjson/url") }}
               pushd cJSON
               mkdir build
               pushd build
diff --git a/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2 b/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2
--- a/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2
+++ b/source/soca/cluster_node_bootstrap/templates/linux/soca_python.sh.j2
@@ -16,6 +16,25 @@ function install_soca_python () {
     log_info "Local SOCA_PYTHON ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} found and at correct version, skipping SOCA_PYTHON Install"
 
   else
+
+    {% if context.get("/configuration/BaseOS") == "amazonlinux2" %}
+       log_info "AmazonLinux2 ships with OpenSSL 1.0.x, bumping to openssl11"
+       if ! verify_package_installed openssl11; then
+         # Note: you need openssl 1.1.x devel, however you cannot install them if openssl 1.0.x devel is already there
+         if verify_package_installed openssl-devel; then
+           log_info "Removing openssl 1.0.x devel"
+           packages_remove openssl-devel
+         fi
+         packages_install openssl11 openssl11-devel
+        log_info "openssl11 is installed on /usr/bin/openssl11, we move the required lib/include to the a different folder: /opt/soca/{{ context.get('/configuration/ClusterId') }}/packages/openssl11/"
+         # Avoid conflict with openssl1.0.x
+         mkdir -p "/opt/soca/{{ context.get('/configuration/ClusterId') }}/packages/openssl11/lib"
+         mkdir -p "/opt/soca/{{ context.get('/configuration/ClusterId') }}/packages/openssl11/include"
+         cp -r /usr/include/openssl "/opt/soca/{{ context.get('/configuration/ClusterId') }}/packages/openssl11/include"
+         cp /usr/lib64/libssl.so.1.1.* /usr/lib64/libcrypto.so.1.1 "/opt/soca/{{ context.get('/configuration/ClusterId') }}/packages/openssl11/lib"
+       fi
+    {% endif %}
+
     log_info "Local SOCA_PYTHON ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} not found, installing it"
     mkdir -p ${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}
     log_info "${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}/bin/python3 not detected or at wrong version, installing Python ${PYTHON_VERSION}"
@@ -25,27 +44,59 @@ function install_soca_python () {
     tar xvf "python3_soca_installer.tgz" --strip-components=1 -C .
 
     {% if context.get("/job/NodeType") == "controller" %}
-      # Add additional compilation flags for Controller as Python will be used for web interface & other tasks
-      if ! ./configure CXX="g++" \
-        LDFLAGS="-L/usr/lib64/openssl" \
-        CPPFLAGS="-I/usr/include/openssl" \
-        CLAGS="fPIC" \
-        --enable-loadable-sqlite-extensions \
-        --prefix=${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} \
-        --enable-optimizations \
-        --enable-shared \
-        --with-ensurepip=install; then
-        exit_fail "Unable to run './configure' for SOCA_PYTHON. Check bootstrap logs."
+      # Full-featured Python build for controller nodes
+      local CXX="g++"
+      local PKG_CONFIG_PATH="/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"
+      local CPPFLAGS="-I/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/sqlite/include"
+      local LDFLAGS="-L/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/sqlite/lib"
+      local ADDITIONAL_ARGS=""
+
+      {% if context.get("/configuration/BaseOS") == "amazonlinux2" %}
+        # ALI2, we use a custom OpenSSL as ALI2 ships with OpenSSL1.0 and we need 1.1
+        # We disable gcov to avoid compilation error when using --enable-optimization with custom sqlite3
+        CPPFLAGS+=" -I/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/openssl11/include"
+        LDFLAGS+=" -L/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/openssl11/lib"
+        CFLAGS+=" -fno-omit-frame-pointer -fno-profile-arcs -fno-test-coverage"
+        ADDITIONAL_ARGS+=" --with-openssl=/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/openssl11"
+        export LD_LIBRARY_PATH="/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/openssl11/lib:$LD_LIBRARY_PATH"
+      {% endif %}
+
+      local PYTHON_CONFIGURE_CMD="./configure"
+      PYTHON_CONFIGURE_CMD+=" CXX=\"${CXX}\""
+      PYTHON_CONFIGURE_CMD+=" PKG_CONFIG_PATH=\"${PKG_CONFIG_PATH}\""
+      PYTHON_CONFIGURE_CMD+=" CPPFLAGS=\"${CPPFLAGS}\""
+      PYTHON_CONFIGURE_CMD+=" LDFLAGS=\"${LDFLAGS}\""
+      PYTHON_CONFIGURE_CMD+=" --enable-loadable-sqlite-extensions"
+      PYTHON_CONFIGURE_CMD+=" --prefix=\"${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}\""
+      PYTHON_CONFIGURE_CMD+=" --enable-shared"
+      PYTHON_CONFIGURE_CMD+=" --enable-optimizations"
+      PYTHON_CONFIGURE_CMD+=" --with-lto"
+      PYTHON_CONFIGURE_CMD+=" --with-ensurepip=install"
+      PYTHON_CONFIGURE_CMD+=" ${ADDITIONAL_ARGS}"
+
+      if ! eval ${PYTHON_CONFIGURE_CMD}; then
+        exit_fail "Unable to run [${PYTHON_CONFIGURE_CMD}] for SOCA_PYTHON. Check bootstrap logs."
       fi
+
     {% else %}
-      # Minimal Python3 environment to build OpenPBS
-      if ! ./configure CXX="g++" \
-        LDFLAGS="-L/usr/lib64/openssl" \
-        CPPFLAGS="-I/usr/include/openssl" \
-        CLAGS="fPIC" \
-        --prefix=${SOCA_PYTHON_LOCAL_INSTALL_PREFIX} \
-        --enable-shared; then
-        exit_fail "Unable to run './configure' for SOCA_PYTHON. Check bootstrap logs."
+      # Minimal Python build for compute nodes
+      local CXX="g++"
+      local PKG_CONFIG_PATH="/opt/soca/{{  context.get("/configuration/ClusterId")  }}/packages/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"
+      local ADDITIONAL_ARGS=""
+
+       {% if context.get("/configuration/BaseOS") == "amazonlinux2" %}
+        ADDITIONAL_ARGS+=" --with-openssl=/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/openssl11"
+        export LD_LIBRARY_PATH="/opt/soca/{{ context.get("/configuration/ClusterId") }}/packages/openssl11/lib:$LD_LIBRARY_PATH"
+       {% endif %}
+
+      local PYTHON_CONFIGURE_CMD="./configure"
+      PYTHON_CONFIGURE_CMD+=" CXX=\"${CXX}\""
+      PYTHON_CONFIGURE_CMD+=" --prefix=\"${SOCA_PYTHON_LOCAL_INSTALL_PREFIX}\""
+      PYTHON_CONFIGURE_CMD+=" --enable-shared"
+      PYTHON_CONFIGURE_CMD+=" ${ADDITIONAL_ARGS}"
+
+      if ! eval ${PYTHON_CONFIGURE_CMD}; then
+        exit_fail "Unable to run [${PYTHON_CONFIGURE_CMD}] for SOCA_PYTHON. Check bootstrap logs."
       fi
     {% endif %}
 
@@ -62,9 +113,10 @@ function install_soca_python () {
     popd
 
     log_info "SOCA_PYTHON installed successfully, updating dynamic linker cache"
+
     # ensure 99- is there to avoid version conflict if /lib64 system python3 is already at the same version
     echo "/lib64" > /etc/ld.so.conf.d/00-system-python.conf # ensure system python is always loaded first
-    echo "/opt/soca/{{ context.get('/configuration/ClusterId') }}/python/latest/lib" > /etc/ld.so.conf.d/99-python-{{ context.get('/configuration/ClusterId') }}.conf
+    echo "/opt/soca/{{ context.get('/configuration/ClusterId') }}/python/latest/lib" > /etc/ld.so.conf.d/99-{{ context.get('/configuration/ClusterId') }}-python.conf
     if ! ldconfig; then
       exit_fail "SOCA_PYTHON installed but unable to update ldconfig. Check bootstrap logs"
     fi
